package com.example.cpdesignautogenerator.writer;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;

import org.apache.poi.ss.usermodel.Workbook;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ExcelWriter {

	public void write(Path outputDirPath, Workbook workbook) {

		Path outputFilePath = outputDirPath.resolve("AutoGenerated.xlsx");

		try (FileOutputStream fileOutputStream = new FileOutputStream(outputFilePath.toFile())) {
			workbook.write(fileOutputStream);

		} catch (IOException e) {
			log.error("エクセルの出力に失敗しました。");
		}

		log.info("エクセルファイルの出力が完了しました。対象ファイル:[{}]", outputFilePath);
	}
}
